os: osx

before_install:
  - brew tap homebrew/cask
  - brew cask install phantomjs
  - git clone git://github.com/n1k0/casperjs.git casperjs
  - export PATH=`pwd`/casperjs/bin/:$PATH

before_script:
  - phantomjs --version
  - casperjs --version
  - python -m SimpleHTTPServer 8080 &
  - sleep 10

script:
  - casperjs test test/integration
